version: '2'

services:
    nginx:
        build: ./nginx-le
        image: umputun/nginx-le:latest
        hostname: nginx
        restart: always
        container_name: nginx

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        volumes:
            - ./etc/ssl:/etc/nginx/ssl
            - ./etc/service-example.conf:/etc/nginx/service.conf

        ports:
            - "80:80"
            - "443:443"

        environment:
            - TZ=America/Chicago
            - LETSENCRYPT=true
            - LE_EMAIL=naznadr72@gmail.com
            - LE_FQDN=www.nefeed.tk
            #- SSL_CERT=le-crt.pem
            #- SSL_KEY=le-key.pem

    front-end:
        build:
            context: ./frontEnd
        depends_on:
            - mongo
            - server
        ports:
            - 8080:8080
    
    article-server:
        build:
            context: ./articaleServer
        depends_on:
            - "mongo"
            - "rabbitmq"
        restart: always
    readability:
        build:
            context: ./readability
        ports:
            - 8000:8000
        restart: always
    butler1:
        build:
            context: ./butler
        depends_on:
            - "mongo"
            - "rabbitmq"
            - "article-server"
    butler2:
        build:
            context: ./butler
        depends_on:
            - "mongo"
            - "rabbitmq"
            - "article-server"
    butler3:
        build:
            context: ./butler
        depends_on:
            - "mongo"
            - "rabbitmq"
            - "article-server"
        
    server:
        build:
            context: ./server
        depends_on:
            - mongo
        ports:
            - 12345:12345
        restart: always
    rabbitmq:
        image: rabbitmq:3.6.12-management
        ports:
            - 5672:5672
            - 15672:15672

    mongo:
        image: mongo:3.4.7
        volumes:
            - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod